package com.misacordes.application.entities;

public enum ChordCategory {
    MAJOR,       // Do, Re, Mi, Fa, Sol, La, Si
    MINOR,       // Cm, Dm, Em, Fm, Gm, Am, Bm
    SEVENTH,     // C7, D7, E7...
    MAJOR_SEVENTH, // Cmaj7, Dmaj7...
    MINOR_SEVENTH, // Cm7, Dm7...
    SUSPENDED,   // Csus4, Dsus2...
    DIMINISHED,  // Cdim, Ddim...
    AUGMENTED,   // Caug, Daug...
    EXTENDED,    // C9, D11, E13...
    ALTERED,     // C7b5, D7#9...
    ADD,         // Cadd9, Dadd11...
    OTHER        // Casos especiales
}
